line-length = 150

[lint]
extend-select = [
    "E",      # pycodestyle (Error)
    "F",      # Pyflakes
    "W",      # pycodestyle (Warning)
    "I",      # isort (Import sorting)
    "B",      # flake8-bugbear (Common bugs)
    "UP",     # pyupgrade (Upgrade syntax for modern Python)
    "N",      # pep8-naming (Naming conventions)
    "RUF",    # Ruff-specific rules
    "C901",   # too-complex (From your snippet)
]

ignore = [
    "N802",   # 
]